export const SET_UI_MODE = 'SET_UI_MODE'
export const SET_UI_LANGUAGE = 'SET_UI_LANGUAGE'

export const SET_JSON_CONFIG = 'SET_JSON_CONFIG'
export const SET_PYTHON_CONFIG = 'SET_PYTHON_CONFIG'

export const SET_SIKULI_PATH = 'SET_SIKULI_PATH'
export const SET_KCAUTO_PATH = 'SET_KCAUTO_PATH'
