export const en = {
  bodyConfig: {
    generalHeader: 'General',
    generalProgram: 'Program',
    generalProgramDesc: 'Program that Kantai Collection is running in (ex: Chrome)',
    generalJSTOffset: 'JST Offset',
    generalJSTOffsetDesc: 'Hours offset from JST',
    scheduledSleepHeader: 'Scheduled Sleep',
    scheduledSleepStartTime: 'Start Time',
    scheduledSleepLength: 'Length',
    scheduledSleepLengthDesc: 'How long to sleep for',
    expeditionsHeader: 'Expeditions',
    expeditionsFleet2: 'Fleet 2',
    expeditionsFleet3: 'Fleet 3',
    expeditionsFleet4: 'Fleet 4',
    pvpHeader: 'PvP',
    combatHeader: 'Combat',
    combatEngine: 'Engine',
    combatMap: 'Map',
    combatFleetMode: 'Fleet Mode',
    combatCombatNodeCount: 'Combat Node Count',
    combatNodeSelect1: 'If at this Node...',
    combatNodeSelect2: '...select this Node',
    combatNodeSelectAdd: 'Add',
    combatNodeSelects: 'All Node Selects',
    combatCustomFormation1: 'If at this Node...',
    combatCustomFormation2: '...select this Formation',
    combatCustomFormationAdd: 'Add',
    combatCustomFormations: 'All Specified Formations',
    combatCustomNightBattle1: 'If at this Node...',
    combatCustomNightBattle2: '...select Night Battle',
    combatCustomNightBattleAdd: 'Add',
    combatCustomNightBattles: 'All Night Battles',
    combatRetreatLimit: 'Retreat Limit',
    combatRepairLimit: 'Repair Limit',
    combatRepairTimeLimit: 'Repair Time Limit',
    combatLBASGroups: 'LBAS Groups',
    combatLBASGroup1Nodes: 'Group 1 Nodes',
    combatLBASGroup2Nodes: 'Group 2 Nodes',
    combatLBASGroup3Nodes: 'Group 3 Nodes',
    combatCheckFatigue: 'Check Fatigue',
    combatReserveDocks: 'Reserve Docks',
    combatPortCheck: 'Port Check',
    combatMedalStop: 'Medal Stop',
    questsHeader: 'Quests',
    configHeader: 'Config',
    configLoad: 'Load',
    configSave: 'Save',
  },
  bodyRunCmd: {
    intro: `Fill out the two fields below to generate the command you need to run in your command prompt/cmd/terminal to
      run kcauto-kai.`,
    sikuliPath: 'Sikuli Path',
    sikuliPathDesc: 'Full path to the folder/directory where Sikuli is installed (where sikulix.jar exists)',
    kcautoKaiPath: 'kcauto-kai Path',
    kcautoKaiPathDesc: 'Full path to the folder/directory where kcauto-kai is installed (where config.ini exists)',
    commandHeader: 'Command',
    noCommandNotice: 'Fill out the above two fields to generate the command.',
  },
  bodyAbout: {
    disclaimerHeader: 'Disclaimer',
    disclaimer1: `kcauto-kai is meant for educational purposes only! Actual and prolonged usage of kcauto-kai may result
      in your account being banned. Remember that botting is against rules! The author of kcauto-kai makes no guarantee
      that the end user will not be caught and penalized for using kcauto-kai, and will not take any responsibility for
      any repercussions that befall the end user. Spamming expeditions and sorties nonstop raises your chances of being
      flagged and banned.`,
    disclaimer2: `In addition, although unlikely, you may lose ships if you allow kcauto-kai to conduct combat sorties.
      While kcauto-kai has been painstakingly designed to reduce the chances of this happening, the author of kcauto-kai
      takes no responsibility regarding the preservation of your ships.`,
  },
}
