export const GITHUB_LINK = 'https://github.com/mrmin123/kcauto'
export const CHANGELOG_LINK = 'https://github.com/mrmin123/kcauto/blob/master/CHANGELOG.md'
export const DISCORD_LINK = 'https://discord.gg/KEHSmUs'
export const KANCOLLE_AUTO_GITHUB_LINK = 'https://github.com/mrmin123/kancolle-auto'
export const PATREON_LINK = 'https://www.patreon.com/mrmin123'
export const MAKERSUPPORT_LINK = 'https://www.makersupport.com/mrmin123'
