// uncomment if JSX and URLs are used
// import React from 'react'
// import * as urls from 'urls'

// This is the template file for creating a localization file for the kcauto-kai webUI.
// Replace TMP below with the 2-letter country code for the language you are providing localization for.
// Refer to the en.jsx file for the content of these fields. Fields set as null or an empty string ('') will
// automatically fall back to the original english localization of that field.
// Once you've made or updated a translation please make a PR on the kcauto-kai Github repository for review. Thank you!

export const TMP = {
  bodyConfig: {
    generalHeader: null,
    generalProgram: null,
    generalProgramDesc: null,
    generalJSTOffset: null,
    generalJSTOffsetDesc: null,
    scheduledSleepHeader: null,
    scheduledSleepStartTime: null,
    scheduledSleepLength: null,
    scheduledSleepLengthDesc: null,
    expeditionsHeader: null,
    expeditionsFleet2: null,
    expeditionsFleet3: null,
    expeditionsFleet4: null,
    pvpHeader: null,
    combatHeader: null,
    combatEngine: null,
    combatEngineLegacy: null,
    combatEngineLive: null,
    combatMap: null,
    combatFleetMode: null,
    combatFleetModeStandard: null,
    combatFleetModeCTF: null,
    combatFleetModeSTF: null,
    combatFleetModeTransport: null,
    combatFleetModeStriking: null,
    combatCombatNodeCount: null,
    combatNodeSelect1: null,
    combatNodeSelect2: null,
    combatNodeSelectAdd: null,
    combatNodeSelects: null,
    combatCustomFormation1: null,
    combatCustomFormation2: null,
    combatCustomFormationAdd: null,
    combatCustomFormations: null,
    combatFormationLineAhead: null,
    combatFormationDoubleLine: null,
    combatFormationDiamond: null,
    combatFormationEchelon: null,
    combatFormationLineAbreast: null,
    combatFormationVanguard: null,
    combatFormationCombinedFleet1: null,
    combatFormationCombinedFleet2: null,
    combatFormationCombinedFleet3: null,
    combatFormationCombinedFleet4: null,
    combatCustomNightBattle1: null,
    combatCustomNightBattle2: null,
    combatCustomNightBattleAdd: null,
    combatCustomNightBattles: null,
    combatNightBattleTrue: null,
    combatNightBattleFalse: null,
    combatDamageStateHeavy: null,
    combatDamageStateModerate: null,
    combatDamageStateMinor: null,
    combatRetreatLimit: null,
    combatRepairLimit: null,
    combatRepairTimeLimit: null,
    combatLBASGroups: null,
    combatLBASGroup1Nodes: null,
    combatLBASGroup2Nodes: null,
    combatLBASGroup3Nodes: null,
    combatCheckFatigue: null,
    combatReserveDocks: null,
    combatPortCheck: null,
    combatMedalStop: null,
    questsHeader: null,
    configHeader: null,
    configLoad: null,
    configSave: null,
  },
  bodyRunCmd: {
    intro: null,
    sikuliPath: null,
    sikuliPathDesc: null,
    kcautoKaiPath: null,
    kcautoKaiPathDesc: null,
    commandHeader: null,
    noCommandNotice: null,
  },
  bodyAbout: {
    intro1: null,
    intro2: null,
    disclaimerHeader: null,
    disclaimer1: null,
    disclaimer2: null,
  },
}
