// localization for the Korean language. Initial translation lifted from an unofficial translation floating around the
// web.

// uncomment if JSX and URLs are used
// import React from 'react'
// import * as urls from 'urls'

export const ko = {
  label: '한국어',
  bodyConfig: {
    generalHeader: '일반 설정',
    generalProgram: '프로그램',
    generalProgramDesc: '칸코레가 실행되는 창 이름 입력 (ex: Chrome)',
    generalJSTOffset: 'JST Offset',
    generalJSTOffsetDesc: 'JST와 시간차이. 한국은 0',
    generalPause: null,
    generalPauseTrue: null,
    generalPauseFalse: null,
    scheduledSleepHeader: '휴식 시간',
    scheduledSleepSleepEnabled: null,
    scheduledSleepSleepStartTime: '시작 시간',
    scheduledSleepSleepLength: '길이',
    scheduledSleepExpeditionSleepEnabled: null,
    scheduledSleepExpeditionSleepStartTime: null,
    scheduledSleepExpeditionSleepLength: null,
    scheduledSleepCombatSleepEnabled: null,
    scheduledSleepCombatSleepStartTime: null,
    scheduledSleepCombatSleepLength: null,
    expeditionsHeader: '원정',
    expeditionsFleet2: '2함대',
    expeditionsFleet3: '3함대',
    expeditionsFleet4: '4함대',
    pvpHeader: '연습',
    combatHeader: '출격',
    combatEngine: null,
    combatEngineLegacy: null,
    combatEngineLive: null,
    combatMap: '해역',
    combatFleetMode: '함대 유형',
    combatFleetModeStandard: '일반',
    combatFleetModeCTF: '기동',
    combatFleetModeSTF: '수상',
    combatFleetModeTransport: '수송',
    combatFleetModeStriking: '유격',
    combatCombatNodeCount: '전투 횟수',
    combatNodeSelect1: '이 마스가 능동분기면...',
    combatNodeSelect2: '...이 마스 선택',
    combatNodeSelectAdd: null,
    combatNodeSelects: '능동분기 선택 설정들',
    combatCustomFormation1: null,
    combatCustomFormation2: null,
    combatCustomFormationAdd: null,
    combatCustomFormations: null,
    combatFormationLineAhead: null,
    combatFormationDoubleLine: null,
    combatFormationDiamond: null,
    combatFormationEchelon: null,
    combatFormationLineAbreast: null,
    combatFormationVanguard: null,
    combatFormationCombinedFleet1: null,
    combatFormationCombinedFleet2: null,
    combatFormationCombinedFleet3: null,
    combatFormationCombinedFleet4: null,
    combatCustomNightBattle1: null,
    combatCustomNightBattle2: null,
    combatCustomNightBattleAdd: null,
    combatCustomNightBattles: null,
    combatNightBattleTrue: null,
    combatNightBattleFalse: null,
    combatDamageStateHeavy: null,
    combatDamageStateModerate: null,
    combatDamageStateMinor: null,
    combatRetreatLimit: '회항 설정',
    combatRepairLimit: '수복 설정',
    combatRepairTimeLimit: '고속수복 시간',
    combatLBASGroups: '출격 기항대',
    combatLBASGroup1Nodes: '제1기항대 마스',
    combatLBASGroup2Nodes: '제2기항대 마스',
    combatLBASGroup3Nodes: '제3기항대 마스',
    combatCheckFatigue: '피로도 체크',
    combatReserveDocks: null,
    combatPortCheck: '모항 체크',
    combatClearStop: '해역클리어 정지',
    shipSwitcherHeader: null,
    shipSwitcherSlot1: null,
    shipSwitcherSlot2: null,
    shipSwitcherSlot3: null,
    shipSwitcherSlot4: null,
    shipSwitcherSlot5: null,
    shipSwitcherSlot6: null,
    shipSwitcherCriteria: null,
    shipSwitcherCriteriaDamage: null,
    shipSwitcherCriteriaFatigue: null,
    shipSwitcherCriteriaSparkle: null,
    shipSwitcherModalSpecification: null,
    shipSwitcherModalSpecificationPosition: null,
    shipSwitcherModalSpecificationShip: null,
    shipSwitcherModalSpecificationClass: null,
    shipSwitcherModalSortBy: null,
    shipSwitcherModalSortByDateAcquired: null,
    shipSwitcherModalSortByClass: null,
    shipSwitcherModalSortByLevel: null,
    shipSwitcherModalOffsetStart: null,
    shipSwitcherModalOffsetStartStart: null,
    shipSwitcherModalOffsetStartEnd: null,
    shipSwitcherModalOffsetCount: null,
    shipSwitcherModalClasses: null,
    shipSwitcherModalShips: null,
    shipSwitcherModalLevel: null,
    shipSwitcherModalLockedIgnore: null,
    shipSwitcherModalLockedYes: null,
    shipSwitcherModalLockedNo: null,
    shipSwitcherModalRingedIgnore: null,
    shipSwitcherModalRingedYes: null,
    shipSwitcherModalRingedNo: null,
    questsHeader: '임무',
    configHeader: '설정',
    configLoad: null,
    configSave: null,
  },
  bodyRunCmd: {
    intro: null,
    sikuliPath: null,
    sikuliPathDesc: null,
    kcautoKaiPath: null,
    kcautoKaiPathDesc: null,
    commandHeader: null,
    noCommandNotice: null,
  },
  bodyAbout: {
    intro1: null,
    intro2: null,
    disclaimerHeader: null,
    disclaimer1: null,
    disclaimer2: null,
  },
}
